stages:
  make_datasets:
    cmd: python src/data/make_dataset.py
    deps:
    - data/external
    - src/data/make_dataset.py
    params:
    - make_dataset.test_size
    outs:
    - data/raw
  preprocess_data:
    cmd: python src/data/preprocess_data.py
    deps:
    - data/raw
    - src/data/preprocess_data.py
    outs:
    - data/processed
  build_features:
    cmd: python src/features./build_features.py
    deps:
    - data/processed
    - src/features/build_features.py
    params:
    - build_features.max_features
    outs:
    - data/interim
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/interim
    - src/models/train_model.py
    outs:
    - models

  predict_model:
    cmd: python src/models/predict_model.py
    deps:
    - src/models/predict_model.py
    - data/interim
    - models
