name: CI Pipeline

on: push

jobs:
  Dvc pipeline run:
    runs-on: Ubuntu-latest
    env:

      # AWS credentials for DVC S3 remote
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps: 
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup Python
      uses: actions/setup-python@v5
      with: 
        python-version: "3.13.7"

    - name: install dependencies
      run: | 
        pip install -r requirements.txt

    - name: pull data from dvc s3 bucket
      run: | 
        dvc pull

    - name: run the dvc pipeline
      run: | 
        dvc repro

