name: CI Pipeline

on: 
  push:
    branches: [ main ]

jobs:
 
  dvc_pipeline_run:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      mlflow_tracking_uri: ${{ secrets.MLFLOW_TRACKING_URI }}

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with: 
        python-version: "3.11"

    - name: Install dependencies
      run: | 
        pip install -r requirements.txt
        pip install dvc[s3] mlflow
        pip install pytest

    - name: Pull data from DVC
      run: dvc pull

    - name: Run DVC pipeline
      run: dvc repro
    
    - name: test_model_loading
      run: pytest scripts/tests/test_model_loading.py

    - name: test_model_performance
      run: pytest scripts/tests/test_model_performance.py

    - name: Download NLTK data
      run: |
            python - <<EOF
            import nltk
            nltk.download('punkt')
            nltk.download('punkt_tab')
            nltk.download('stopwords')

            EOF
    
    - name: Start FastAPI server
      run: |
          nohup uvicorn backend.app:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &

          echo "Waiting for server to start..."
          for i in {1..15}; do
            if curl -s http://127.0.0.1:8000/docs > /dev/null; then
              echo "Server is up!"
              break
            fi
            sleep 3
          done

    - name: Test API endpoints
      run: pytest scripts/tests/test_backend_api.py

    - name: Show server logs on failure
      if: failure()
      run: cat server.log

    - name: push to  dvc
      run : dvc push

    - name: configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Commit and push changes
      if: ${{github.actor != 'github-actions[bot]'}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Update DVC pipeline results [skip ci]" || echo "No changes to commit"
        git push origin ${{github.ref_name}}
